### ISSUE TITLE
Demo has JS errors!

### ISSUE THREAD

**Issue by aadrian** [kwasniew/hyperapp-realworld-example-app#1]
Clicking in the demo https://hyperapp.netlify.com/ on the heart icon, results in a JS error:
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

**Comment by kwasniew** [comment]
@aadrian Since I couldn't find the spec for this scenario I modelled the original behaviour after the React/Redux version. Since you posted this issue I checked what other frameworks do (Angular, Elm and Vue) and added redirect to login screen which makes more sense to me. There's an open issue https://github.com/gothinkster/realworld/issues/269 to add some automated tests that would keep different realworld versions in sync. Currently the only spec is a textual description that doesn't cover all scenarios.

**Comment by aadrian** [comment]
> ... added redirect to login screen which makes more sense to me.

+1 . That's what the other implementations should have done too, since this is about the "real world" :) .
